#!/usr/bin/env bash

# please adjust the rate and duration

./traffic_gen https://postman-echo.com/post ./request.log | vegeta attack -header "Content-Type: application/json" -keepalive -rate=1/s -duration=10s -lazy -format=json | tee results.bin | vegeta report